### ISSUE TITLE
Test suite failures on Debian buildd

### ISSUE THREAD

**Issue by xolox** [xolox/lua-apr#5]
The Lua/APR binding now has [an official Debian package](http://packages.qa.debian.org/l/lua-apr.html) thanks to Enrico Tassi and as a consequence of this the Lua/APR binding is now being built on a diverse range of architectures. Unfortunately the test suite currently [fails and/or crashes](https://buildd.debian.org/status/package.php?p=lua-apr) on several of these architectures. I'm not familiar with Debian policies so I don't know if this can block the package from becoming available on architectures where it does work, but clearly these problems should be fixed where possible.
- **amd64**: OK
- **armel**: Now works because of 277f8f3c30ef01ac46db6e4f3076142e2a1a1aca
- **hurd-i386**: Process tests fail with `test/proc.lua:59: Forked child failed to create file?!`
- **i386**: OK
- **ia64**: OK
- **kfreebsd-amd64**: OK
- **kfreebsd-i386**: OK
- **mips**: Now works because of 277f8f3c30ef01ac46db6e4f3076142e2a1a1aca
- **mipsel**: Process tests fail with `test/proc.lua:59: Forked child failed to create file?!`
- **powerpc**: Now works, probably because of 8f3fdf220b0cdf8678fce84e85bd27073ab8a644
- **s390**: OK
- **sparc**: Now works because of 277f8f3c30ef01ac46db6e4f3076142e2a1a1aca

**Comment by xolox** [comment]
About the **hurd-i386** build: It seems that [this Debian bug report](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=578432)  might be applicable. If this is the case, maybe linking to `-lpthread` can solve the issue. I'm not sure how to do this selectively on **hurd-i386** though...

**Comment by xolox** [comment]
<del>About the **powerpc** build: Maybe `apr_proc_fork()` is just broken on this architecture, or it may be an interaction between the APR and Lua libraries and the `fork()` system call?!</del>

<ins>This turned out to be a stupid bug on my part, see 138a5dfd3524ac4c05804af009034c2078072f7c.</ins>

**Comment by xolox** [comment]
About the crashes on **mips**, **mipsel** and **sparc**: I'm wondering whether it's possible to run the test suite in such a way that it will produce a backtrace after a crash, this might make the underlying problem more visible...

**Comment by xolox** [comment]
I've e-mailed Enrico with my preliminary results on this issue and he'll update the Debian package soon so hopefully I'll then have backtraces to help me debug the test suite crashes. In the meantime I'm thinking some of the crashes may be related to [endianness](http://en.wikipedia.org/wiki/Endianness), however after writing the table below I'm not really seeing a pattern :-(

| **Architecture** | **Endianness** | **Status** |
| --- | --- | --- |
| **[amd64](http://en.wikipedia.org/wiki/X86-64#AMD64)** | Little | OK |
| **[armel](http://en.wikipedia.org/wiki/ARM_architecture)** | Little | thread tests fail |
| **[hurd-i386](http://en.wikipedia.org/wiki/GNU_Hurd)** | Little? | test suite fails to initialize with `Assertion __pthread_threads failed` followed by an abort |
| **[i386](http://en.wikipedia.org/wiki/IA-32)** | Little | OK |
| **[ia64](http://en.wikipedia.org/wiki/Itanium#Architecture)** | Selectable | OK |
| **kfreebsd-amd64** | Little | OK |
| **kfreebsd-i386** | Little | OK |
| **[mips](http://en.wikipedia.org/wiki/MIPS_architecture)** | Bi-endian | <del>thread_queue tests exit with bus error</del> (<ins>now fixed, see below</ins>) |
| **[mipsel](http://en.wikipedia.org/wiki/MIPSel)** | Little | thread_queue tests exit with bus error |
| **[powerpc](http://en.wikipedia.org/wiki/PowerPC)** | Big | <del>process tests fail with `test/proc.lua:59: Forked child failed to create file?!`</del> (<ins>now fixed, see below</ins>) |
| **[s390](http://en.wikipedia.org/wiki/S390)** | Big | OK |
| **[sparc](http://en.wikipedia.org/wiki/SPARC)** | Big | thread tests exit with bus error |

**Comment by xolox** [comment]
I just got an e-mail from Enrico that the Debian buildd system has been updated to Lua/APR 0.17.5 (8f3fdf220b0cdf8678fce84e85bd27073ab8a644 two commits up). The good news is that the **mips** and **powerpc** builds now pass the test suite, however the curious thing about this is that I'm not sure how I fixed them... Some possibilities:
- The compile warning fixes in 775d7e17ace4e072d98dfc27dffde32eeafd539c actually had an effect besides silencing warnings;
- The change to compile with `apr-1-config --cflags` in 8f3fdf220b0cdf8678fce84e85bd27073ab8a644 fixed the builds (which would be a fortunate coincidence because I intended this change to fix the **hurd-i386** issue which it didn't);
- The tests have timing issues and the build machines were less busy this time around...

**Comment by xolox** [comment]
About the **hurd-i386** issue: I reread the [Debian bug report](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=578432) I linked to previously and realized that Lua/APR won't work on this architecture unless `/usr/bin/lua` is compiled with `-pthread`, however the Lua executable is installed by the `lua5.1` package and I'm not sure the Debian build infrastructure is okay with rebuilding the Lua interpreter for one specific architecture and package (we'll see).

**Comment by xolox** [comment]
By the way I just found out that in addition to the [Debian buildd logs](https://buildd.debian.org/status/package.php?p=lua-apr) there's also the [Debian-Ports buildd logs](http://buildd.debian-ports.org/status/package.php?p=lua-apr) which includes the following architectures: alpha, armhf, avr32, hppa, m68k, powerpcspe, sh4, sparc64. Currently Lua/APR only works on powerpcspe, however I'm pretty sure some of these architectures aren't even supported by the Apache Portable Runtime so Lua/APR will never support all of these architectures/platforms.

**Comment by xolox** [comment]
Some updates:
- Enrico changed the **hurd-i386** Lua package to be linked with `-pthread` so the test suite finally runs on that platform
- The recent fix for unaligned memory access in the serialization module (277f8f3c30ef01ac46db6e4f3076142e2a1a1aca) improved the situation significantly
- I just committed 138a5dfd3524ac4c05804af009034c2078072f7c which should fix the failing `apr.proc_fork()` test

**Comment by xolox** [comment]
The commits from my previous messages have just been tested on the Debian machines and it looks like _all previous build issues have been resolved!_ :-)

However the Lua/APR test suite now fails on kfreebsd because of the new signal handling module; two steps forward, one step back :-(

**Comment by a-zb** [comment]
Hey, I installed it via luarocks and I see tests failing in memcached module:

stack traceback:
    [C]: in function 'assert'
    /usr/local/share/lua/5.1/apr/test/memcache.lua:101: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/apr/test/init.lua:68: in function </usr/local/share/lua/5.1/apr/test/init.lua:54>
    (command line):1: in main chunk

Update: I installed it via luarocks from github and saw it fail again. I looked at the memcached server log and it was failing on the delete command. The memcached protocol changed and the default timeout of 10 is causing the error. To make the tests succeed, I had to change client:delete(key) to client:delete(key,0).

**Comment by xolox** [comment]
@arekzb: Thanks for the bug report and update. I just made a minor change to the memcache tests to retry failing `delete()` calls with a `delete(..., 0)` call before letting the test fail. Can you provide any references about the protocol change or maybe show me the server log entry? I searched for a while but didn't find anything useful. I'm basically wondering whether this is a bug in Lua/APR, the test suite, the underlying APR library or if maybe it's not a bug at all...

**Comment by xolox** [comment]
I'm closing this issue as the Debian builds have been running fine for quite a while now and to the best of my knowledge the memcache problem has also been resolved.
