### ISSUE TITLE
Some platform not support ldap, please see patch.

### ISSUE THREAD

**Issue by zhaozg** [xolox/lua-apr#6]
Hi, Peter, 

   I use APR_HAS_LDAP to decide weather to support ldap. 

[root@tas ~]# diff xolox-lua-apr-2006379 lua-apr -r 
Only in lua-apr: doc
diff -r xolox-lua-apr-2006379/src/ldap.c lua-apr/src/ldap.c
34a35

> # if APR_HAS_LDAP
> 
> 1035a1037
> # endif /\* APR_HAS_LDAP */
> 
> diff -r xolox-lua-apr-2006379/src/lua_apr.c lua-apr/src/lua_apr.c
> 32a33
> # if APR_HAS_LDAP
> 
> 33a35
> # endif
> 
> 147a150
> # if APR_HAS_LDAP
> 
> 152a156
> # endif
> 
> diff -r xolox-lua-apr-2006379/src/lua_apr.h lua-apr/src/lua_apr.h
> 221a222
> # if APR_HAS_LDAP
> 
> 222a224
> # endif
> 
> 338a341
> # if APR_HAS_LDAP
> 
> 343a347
> # endif

**Comment by xolox** [comment]
Thanks for the patch! I've just included your suggested changes.
