### ISSUE TITLE
Support for pollset module

### ISSUE THREAD

**Issue by xolox** [xolox/lua-apr#8]
[For a while now](http://news.ycombinator.com/item?id=2744399) I've wanted to add support for the [APR pollset module](http://apr.apache.org/docs/apr/trunk/group__apr__poll.html) to enable asynchronous network communication. I'm not exactly sure yet how much work is involved but I intend for the pollset module to be next module I support in Lua/APR.

**Comment by zhaozg** [comment]
Good module, Just need it,

**Comment by xolox** [comment]
I've now finished the pollset module including documentation, tests and an example so I'm closing this issue.
